@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NjY3ZjRhMC1mYjI5LTRhYmUtYTc3MC1mYTkwMjJiYTQ3N2EiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI4ZTRhM2JhZC0yZGQ3LTQ3MTctODQyMC0yNzQzYzA4OWMxYjUiLCJleHAiOjE3MjUzMDM3NjgsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.dfTjrPRtmrEW8-pHuucPiK2NUtJIsN7HcuIGyNSW83c
@saleId = a3ed80b6-02a3-4c3c-8286-1ca6d2f2f5b0

DELETE  {{host}}/sale/{{saleId}}
Content-Type: application/json
Authorization: Bearer {{token}}
