@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWU4NmJjNS04MTIxLTQ2NGYtYTVlZi00MmM2YWZkZjA0MzYiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI1M2FkODNmYy0wYzMzLTRhZjAtOWNjMS1lMzQ2ZTYzZGU1MTciLCJleHAiOjE3MjUzMTY3MjEsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.sar0xjI3p-3mbhfbxzdPEJDB0IeY-jQ0iEuUaMvcKoc
@saleId = b9847ebf-015e-4b50-b212-3eaa1127d971

GET {{host}}/sale/{{saleId}}
Content-Type: application/json
Authorization: Bearer {{token}}
