@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjBlMzAxMi05YThhLTRlNWEtYmEzMC04M2Q0YWNjYjY0NDMiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI4OWFlZmMyNi04M2Q0LTQ1MTMtYjM3ZS03YTdmYzlmMmY2ZGQiLCJleHAiOjE3MjUyMzQxMjMsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.SKwj0gaHnen3pUpEJ4MZ9zr-dJkY7D_vxHsEHxkO624

POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Laptop X200",
  "Description": "Una laptop de alto rendimiento con 16GB de RAM y 512GB de SSD.",
  "Stock": 50,
  "Price": {
    "Amount": 1200.99,
    "Currency": "PEN",
    "UnitOfMeasure": "Unidad"
  },
  "Location": {
    "Name": "Tienda Don Ramon",
    "Address": "Avenida Pucallpa 1213",
    "latitude": 52.520008,
    "longitude": 13.404954
  }
}
