@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYjAzY2E3MS1jNzA0LTRjN2ItYjc2ZC0wZTZhNWExZmFjYjMiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI1NmU5YWEzZS1mYmViLTQ1MzUtYjRiYi1mMGI1NTJmNWU2NmIiLCJleHAiOjE3MjUzMTU1OTgsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.0o_1jTolqrzaOmlK8Jfhh0TgfArBWvu6Gk_Zfg5Uj7M

POST {{host}}/product/single
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Laptop X200",
  "Description": "Una laptop de alto rendimiento con 16GB de RAM y 512GB de SSD.",
  "Stock": 50,
  "Price": {
    "Amount": 1200.99,
    "Currency": "PEN",
    "UnitOfMeasure": "Unidad"
  },
  "Location": {
    "Name": "Tienda Don Ramon",
    "Address": "Avenida Pucallpa 1213",
    "latitude": 52.520008,
    "longitude": 13.404954
  }
}
