@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MjNiMGZjZi1jMDI4LTQyZTAtYWU1Yy01ODM5YmZlMGQxNmMiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI1MTJjMmZhMC1jYzlmLTQzYTQtYWU4My0wZmE0ZTY5NWM2YWYiLCJleHAiOjE3MjUyMzI0NTMsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.Uj-hLLolMPoIPr-7o5FXcOoXu0_GtgAXzJYkDltwt98

POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Laptop X200",
  "Description": "Una laptop de alto rendimiento con 16GB de RAM y 512GB de SSD.",
  "Stock": 50,
  "Price": {
    "Amount": 1200.99,
    "Currency": "PEN",
    "UnitOfMeasure": "Unidad"
  },
  "Location": {
    "Name": "Tienda Don Ramon",
    "Address": "Avenida Pucallpa 1213",
    "latitude": 52.520008,
    "longitude": 13.404954
  }
}
