@host = http://localhost:5180
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYjAzY2E3MS1jNzA0LTRjN2ItYjc2ZC0wZTZhNWExZmFjYjMiLCJnaXZlbl9uYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJSb2RyaWd1ZXoiLCJqdGkiOiI1NmU5YWEzZS1mYmViLTQ1MzUtYjRiYi1mMGI1NTJmNWU2NmIiLCJleHAiOjE3MjUzMTU1OTgsImlzcyI6IkluY2FGYyIsImF1ZCI6IkluY2FGYyJ9.0o_1jTolqrzaOmlK8Jfhh0TgfArBWvu6Gk_Zfg5Uj7M
@productId = eac9421f-efea-4d8c-9d2c-6288621301b8

GET {{host}}/product/{{productId}}
Content-Type: application/json
Authorization: Bearer {{token}}
